{
 "title": "Router Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(routeros_interface_running,instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(routeros_interface_running{type=~\"ether|wifi\"},interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_system_uptime_seconds{instance=\"$Instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Load %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_per_cpu_load{instance=\"$Instance\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Load %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_cpu_load{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_memory_total_bytes{instance=\"$Instance\"} - routeros_memory_free_bytes{instance=\"$Instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "routeros_memory_total_bytes{instance=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_disk_total_bytes{instance=\"$Instance\"} - routeros_disk_free_bytes{instance=\"$Instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "routeros_disk_total_bytes{instance=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "routeros_per_cpu_load{instance=\"$Instance\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "routeros_memory_total_bytes{instance=\"$Instance\"} - routeros_memory_free_bytes{instance=\"$Instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "routeros_memory_total_bytes{instance=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "routeros_disk_total_bytes{instance=\"$Instance\"} - routeros_disk_free_bytes{instance=\"$Instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "routeros_disk_total_bytes{instance=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Interface Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "routeros_interface_running{type=\"ether\", instance=\"$Instance\"}",
     "legendFormat": "{{interface}}"
    },
    {
     "expr": "routeros_interface_running{type=\"wifi\", instance=\"$Instance\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "BGP Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "routeros_bgp_session_up{instance=\"$Instance\"}",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_fw_connections{instance=\"$Instance\"}",
     "legendFormat": "Connection Count"
    }
   ]
  },
  { "title": "$Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "Interface" },
  {
   "title": "Link UP",
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "routeros_interface_running{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Traffic Bits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "routeros_interface_tx_bps{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "TX"
    },
    {
     "expr": "routeros_interface_rx_bps{instance=\"$Instance\", interface=\"$Interface\"} * -1",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Traffic Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "routeros_interface_tx_pps{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "TX"
    },
    {
     "expr": "routeros_interface_rx_pps{instance=\"$Instance\", interface=\"$Interface\"} * -1",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_interface_tx_bytes{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "TX"
    },
    {
     "expr": "routeros_interface_rx_bytes{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Total Packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routeros_interface_tx_packets{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "TX"
    },
    {
     "expr": "routeros_interface_rx_packets{instance=\"$Instance\", interface=\"$Interface\"}",
     "legendFormat": "RX"
    }
   ]
  }
 ]
}